apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - github.com/prometheus-operator/kube-prometheus?ref=release-0.13
patchesStrategicMerge:
  - grafana-patch.yaml
  - prometheus-patch.yaml
  - alertmanager-patch.yaml
